### GENERAL SETTINGS ###

# Site settings
title: Ben Windley
description: "Learning, Drawing, Programming"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "https://BenWindley.github.io/"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
future: true

colors:  #in hex code if not noted else
  primary: "#7B8A51" #Top Bar 
  primary_rgb: "123,138,81" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#000000" #"#33004D"
  link: "#7B8A51"
  link_hover: "#7B8A51"
  footer_heading: "#7B8A51"
  footer_content: "#7B8A51"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: https://twitter.com/benwindley
  - title: linkedin
    url: https://www.linkedin.com/in/ben-windley

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: ben.windley@yahoo.co.uk

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Ben Windley
    position: Masters Student
    text: I'm learning programming and game design! 
    img: watermelon.png
    social:
      - title: envelope #use for email address
        url: mailto:ben.windley@yahoo.co.uk
      - title: twitter
        url: http://twitter.com/BenWindley
      - title: linkedin
        url: https://www.linkedin.com/in/ben-windley
 
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: Learning, Drawing, Programming