### GENERAL SETTINGS ###

# Site settings
title: Ben Windley
description: ""
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "https://BenWindley.github.io/"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
future: true

colors:  #in hex code if not noted else
  primary: "#613053" #Top Bar 
  primary_rgb: "123,138,81" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#000000" #"#33004D"
  link: "#613053"
  link_hover: "#613053"
  footer_heading: "#613053"
  footer_content: "#613053"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ben-windley

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: ben.windley@yahoo.co.uk

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Ben Windley
    position: Game Developer
    text: (not a bird)
    img: Bard_large.png
    social:
      - title: envelope #use for email address
        url: mailto:ben.windley@yahoo.co.uk
      - title: linkedin
        url: https://www.linkedin.com/in/ben-windley
 
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: 